"""add login logs

Revision ID: 44f2a46ca888
Revises: 6f5d2fd5486a
Create Date: 2026-07-28 14:11:33.346399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '44f2a46ca888'
down_revision: Union[str, None] = '6f5d2fd5486a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kullanici_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('basarili_mi', sa.Boolean(), nullable=False),
    sa.Column('ip_adresi', sa.String(length=50), nullable=True),
    sa.Column('kullanici_aracisi', sa.String(length=500), nullable=True),
    sa.Column('zaman', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_logs')
    # ### end Alembic commands ###
