"""ilk_sema

Revision ID: 84702315e08b
Revises: 
Create Date: 2026-07-23 09:55:39.754905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '84702315e08b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ilceler',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('il', sa.String(length=100), nullable=False),
    sa.Column('merkez_enlem', sa.Float(), nullable=False),
    sa.Column('merkez_boylam', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad')
    )
    op.create_table('kategoriler',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ad', sa.String(length=150), nullable=False),
    sa.Column('aciklama', sa.String(length=500), nullable=True),
    sa.Column('ikon', sa.String(length=100), nullable=True),
    sa.Column('sorumlu_departman', sa.String(length=150), nullable=False),
    sa.Column('renk', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad')
    )
    op.create_table('kullanicilar',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('soyad', sa.String(length=100), nullable=False),
    sa.Column('tc_kimlik_no', sa.String(length=11), nullable=True),
    sa.Column('e_posta', sa.String(length=255), nullable=False),
    sa.Column('telefon', sa.String(length=20), nullable=False),
    sa.Column('sifre_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('vatandas', 'personel', 'admin', name='kullanici_rolu'), nullable=False),
    sa.Column('profil_fotografi', sa.String(length=500), nullable=True),
    sa.Column('adres', sa.String(length=500), nullable=True),
    sa.Column('departman', sa.String(length=150), nullable=True),
    sa.Column('aktif_mi', sa.Boolean(), nullable=False),
    sa.Column('e_posta_dogrulandi_mi', sa.Boolean(), nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('guncellenme_tarihi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('son_giris_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tc_kimlik_no')
    )
    op.create_index(op.f('ix_kullanicilar_e_posta'), 'kullanicilar', ['e_posta'], unique=True)
    op.create_table('aktivite_kayitlari',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kullanici_id', sa.UUID(), nullable=False),
    sa.Column('eylem', sa.String(length=100), nullable=False),
    sa.Column('hedef_tablo', sa.String(length=100), nullable=False),
    sa.Column('hedef_id', sa.UUID(), nullable=True),
    sa.Column('detay', sa.String(length=1000), nullable=True),
    sa.Column('ip_adresi', sa.String(length=45), nullable=True),
    sa.Column('olusturulma_tarihi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mahalleler',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ad', sa.String(length=150), nullable=False),
    sa.Column('ilce_id', sa.UUID(), nullable=False),
    sa.Column('merkez_enlem', sa.Float(), nullable=False),
    sa.Column('merkez_boylam', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ilce_id'], ['ilceler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talepler',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('takip_no', sa.String(length=20), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=False),
    sa.Column('aciklama', sa.Text(), nullable=False),
    sa.Column('kategori_id', sa.UUID(), nullable=False),
    sa.Column('mahalle_id', sa.UUID(), nullable=False),
    sa.Column('adres_detay', sa.String(length=500), nullable=True),
    sa.Column('enlem', sa.Float(), nullable=False),
    sa.Column('boylam', sa.Float(), nullable=False),
    sa.Column('oncelik', sa.Enum('dusuk', 'orta', 'yuksek', 'acil', name='talep_onceligi'), nullable=False),
    sa.Column('durum', sa.Enum('bekliyor', 'inceleniyor', 'atandi', 'cozuldu', 'kapatildi', name='talep_durumu'), nullable=False),
    sa.Column('ai_onerilen_kategori_id', sa.UUID(), nullable=True),
    sa.Column('ai_onerilen_oncelik', sa.Enum('dusuk', 'orta', 'yuksek', 'acil', name='ai_onerilen_oncelik'), nullable=True),
    sa.Column('ai_guven_skoru', sa.Float(), nullable=True),
    sa.Column('olusturan_id', sa.UUID(), nullable=False),
    sa.Column('cozum_notu', sa.Text(), nullable=True),
    sa.Column('cozulme_tarihi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('olusturulma_tarihi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('guncellenme_tarihi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_onerilen_kategori_id'], ['kategoriler.id'], ),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategoriler.id'], ),
    sa.ForeignKeyConstraint(['mahalle_id'], ['mahalleler.id'], ),
    sa.ForeignKeyConstraint(['olusturan_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_talepler_takip_no'), 'talepler', ['takip_no'], unique=True)
    op.create_table('ai_kayitlari',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kullanici_id', sa.UUID(), nullable=True),
    sa.Column('ilgili_talep_id', sa.UUID(), nullable=True),
    sa.Column('islem_turu', sa.String(length=50), nullable=False),
    sa.Column('girdi_metni', sa.Text(), nullable=False),
    sa.Column('cikti_metni', sa.Text(), nullable=False),
    sa.Column('model_adi', sa.String(length=100), nullable=False),
    sa.Column('yanit_suresi_ms', sa.Integer(), nullable=True),
    sa.Column('guven_skoru', sa.Float(), nullable=True),
    sa.Column('olusturulma_tarihi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ilgili_talep_id'], ['talepler.id'], ),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atamalar',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('talep_id', sa.UUID(), nullable=False),
    sa.Column('personel_id', sa.UUID(), nullable=False),
    sa.Column('atayan_id', sa.UUID(), nullable=False),
    sa.Column('not', sa.String(length=500), nullable=True),
    sa.Column('olusturulma_tarihi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['atayan_id'], ['kullanicilar.id'], ),
    sa.ForeignKeyConstraint(['personel_id'], ['kullanicilar.id'], ),
    sa.ForeignKeyConstraint(['talep_id'], ['talepler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bildirimler',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kullanici_id', sa.UUID(), nullable=False),
    sa.Column('tur', sa.Enum('yeni_talep', 'durum_degisti', 'talep_atandi', 'talep_cozuldu', 'sistem', name='bildirim_turu'), nullable=False),
    sa.Column('baslik', sa.String(length=200), nullable=False),
    sa.Column('mesaj', sa.String(length=500), nullable=False),
    sa.Column('ilgili_talep_id', sa.UUID(), nullable=True),
    sa.Column('okundu_mu', sa.Boolean(), nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ilgili_talep_id'], ['talepler.id'], ),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('durum_gecmisi',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('talep_id', sa.UUID(), nullable=False),
    sa.Column('onceki_durum', sa.Enum('bekliyor', 'inceleniyor', 'atandi', 'cozuldu', 'kapatildi', name='onceki_durum'), nullable=True),
    sa.Column('yeni_durum', sa.Enum('bekliyor', 'inceleniyor', 'atandi', 'cozuldu', 'kapatildi', name='yeni_durum'), nullable=False),
    sa.Column('aciklama', sa.String(length=500), nullable=True),
    sa.Column('degistiren_id', sa.UUID(), nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['degistiren_id'], ['kullanicilar.id'], ),
    sa.ForeignKeyConstraint(['talep_id'], ['talepler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talep_dosyalari',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('talep_id', sa.UUID(), nullable=False),
    sa.Column('dosya_turu', sa.Enum('fotograf', 'video', 'ses', 'belge', 'sonuc_fotografi', name='dosya_turu'), nullable=False),
    sa.Column('dosya_yolu', sa.String(length=500), nullable=False),
    sa.Column('orijinal_ad', sa.String(length=255), nullable=False),
    sa.Column('boyut_bayt', sa.BigInteger(), nullable=False),
    sa.Column('yukleyen_id', sa.UUID(), nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['talep_id'], ['talepler.id'], ),
    sa.ForeignKeyConstraint(['yukleyen_id'], ['kullanicilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('talep_dosyalari')
    op.drop_table('durum_gecmisi')
    op.drop_table('bildirimler')
    op.drop_table('atamalar')
    op.drop_table('ai_kayitlari')
    op.drop_index(op.f('ix_talepler_takip_no'), table_name='talepler')
    op.drop_table('talepler')
    op.drop_table('mahalleler')
    op.drop_table('aktivite_kayitlari')
    op.drop_index(op.f('ix_kullanicilar_e_posta'), table_name='kullanicilar')
    op.drop_table('kullanicilar')
    op.drop_table('kategoriler')
    op.drop_table('ilceler')
    # ### end Alembic commands ###
