"""login audit log eklendi

Revision ID: a159d0989056
Revises: 6f5d2fd5486a
Create Date: 2026-07-28 13:29:44.098704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a159d0989056'
down_revision: Union[str, None] = '6f5d2fd5486a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
