"""refresh token tablosu eklendi

Revision ID: c8cfaf38d80f
Revises: 40cf0e7790f7
Create Date: 2026-07-28 10:39:56.983230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c8cfaf38d80f'
down_revision: Union[str, None] = '40cf0e7790f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokenlar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kullanici_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('olusturulma_tarihi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('son_kullanma_tarihi', sa.DateTime(timezone=True), nullable=False),
    sa.Column('iptal_edildi', sa.Boolean(), nullable=False),
    sa.Column('ip_adresi', sa.String(length=45), nullable=True),
    sa.Column('kullanici_aracisi', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['kullanici_id'], ['kullanicilar.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokenlar_kullanici_id'), 'refresh_tokenlar', ['kullanici_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokenlar_token_hash'), 'refresh_tokenlar', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokenlar_token_hash'), table_name='refresh_tokenlar')
    op.drop_index(op.f('ix_refresh_tokenlar_kullanici_id'), table_name='refresh_tokenlar')
    op.drop_table('refresh_tokenlar')
    # ### end Alembic commands ###
